### ISSUE TITLE
Hi! Is this project is still alive?

### ISSUE THREAD

**Issue by beibao233** [jscuster/PyMouth#1]
Hi there. I'm a student from China.

Recently, I learned about the SAM. And I also want to make a python implementation of it.
Then, I searched has anyone had done it before. 
Not surprisingly, I have found this repository. It's like an unfinished project as I can tell.
If you still want to finish it or if I missed something about this project. 
Please let me know.

I'm very excited about the opportunity to work with others.
My Discord ID is beibao233#3129.

Thanks!

**Comment by jscuster** [comment]
Hi there!I started it but haven't taken it anywhere. Now I know someone's interested I'll get busy! I sent a friend request on discord. Projects are much more fun when there's someone to work with, so please feel free to code with me. Just drop a pull request.

Thank you for asking, Sorry for taking forever to get back to you.
Jason

**Comment by beibao233** [comment]
It's my pleasure. See you on the discord.
